# Generated by Django 4.0.2 on 2022-02-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='desciption',
            new_name='description',
        ),
    ]
